local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"

if not vim.uv.fs_stat(lazypath) then
  error("lazy.nvim is not installed at " .. lazypath)
end

vim.opt.rtp:prepend(lazypath)
vim.opt.termguicolors = true
require("lazy").setup("plugins")

-- Apply the colorscheme generated by `theme` (themes engine). pcall so a
-- missing file (before the first `theme` run) doesn't error.
pcall(function() require("generated_theme") end)
