# floats for common dialogs / utilities
windowrulev2 = float, class:^(pavucontrol)$
windowrulev2 = float, class:^(nm-connection-editor)$
windowrulev2 = float, class:^(blueman-manager)$
windowrulev2 = float, title:^(Open File)$
windowrulev2 = float, title:^(Save File)$
windowrulev2 = float, class:^(org.kde.polkit-kde-authentication-agent-1)$

# a little transparency on terminals looks nice with blur
windowrulev2 = opacity 0.94 0.86, class:^(kitty)$
